// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsY3-gWBYgQtgcRF6lhPB76m0dNiYdxE',
    appId: '1:315151523995:web:e0d5bb48873e997077663e',
    messagingSenderId: '315151523995',
    projectId: 'flutter-w10-3th-final2',
    authDomain: 'flutter-w10-3th-final2.firebaseapp.com',
    storageBucket: 'flutter-w10-3th-final2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPYXo9HH98RXkTblgMH4Iz3HuzWTrG1A',
    appId: '1:315151523995:android:76359597980ec10377663e',
    messagingSenderId: '315151523995',
    projectId: 'flutter-w10-3th-final2',
    storageBucket: 'flutter-w10-3th-final2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5dWJGptIjULRhS2qfvMBghKRI5zXYOA',
    appId: '1:315151523995:ios:5789b59f5eff67ce77663e',
    messagingSenderId: '315151523995',
    projectId: 'flutter-w10-3th-final2',
    storageBucket: 'flutter-w10-3th-final2.appspot.com',
    iosBundleId: 'com.example.flutterW103thXClone',
  );
}
